# Generated by Django 6.0 on 2025-12-19 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_resume', '0003_alter_resume_certifications_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
